void setup()
{
  pinMode(LED_BUILTIN, OUTPUT);                           // Configuring pin...
}

void loop()
{
  digitalWrite(LED_BUILTIN, HIGH);                        // Turning the LED on...
  delay(1000);                                            // Waiting for a second...
  digitalWrite(LED_BUILTIN, LOW);                         // Turning the LED off...
  delay(1000);                                            // Waiting for a second...
}
