#include <Servo.h>                                        // Including servo library...

Servo myservo;                                            // Creating servo object to control a servo...
unsigned long tic;                                        // "tic" time [us].
unsigned long toc;                                        // "toc" time [us].
unsigned int gap;                                         // "gap" time [us].
unsigned long period;                                     // "period" time [us].

void setup()
{
  pinMode(LED_BUILTIN, OUTPUT);                           // Configuring LED pin...
  pinMode(A0, INPUT);                                     // Configuring input pin...
  pinMode(3, OUTPUT);                                     // Configuring output pin...
  myservo.attach(3);                                      // Attaching the servo on pin 3 to the servo object...
  period = 10000;                                         // Setting period time [us]...
}

void loop()
{
  int value;                                              // Analog value.
  
  tic = micros();                                         // Getting "tic" time...
  value = analogRead(A0);                                 // Reading analog value...
  value = map(value, 0, 1023, 0, 180);                    // Scaling it for use with the servo (value between 0 and 180)...
  myservo.write(value);                                   // Setting the servo position according to the scaled value...
  toc = micros();                                         // Getting "toc" time...
  gap = period - (toc - tic);                             // Computing "gap" time...
  
  if(gap > 0)                                             // We are in time...
  {
    delayMicroseconds(gap);                               // Waiting for "gap" time to expire...
  }
  else                                                    // We are late!
  {
    digitalWrite(LED_BUILTIN, HIGH);                      // Turning the LED on...
  }
}
